- src/contexts/OrderingThemeContext/index.js
Story: https://app.asana.com/0/1164464536714178/1207835887820173/f
> [FEAT] fix-color-theme

- src/components/AddressForm/index.js
- Initialize uuidv4 state with a generated value using the v4 function from the uuid library.
- Update property access in the address object to match changes in the API response structure.
- Add new properties (zipcode, neighborhood, map_data) to the address object.
- Update the map_data property to include the library and place_id fields.
> refactor: Update AddressForm component

- src/components/AddressForm/index.js
- src/components/AppleLogin/index.js
- src/components/BusinessList/index.js
- src/components/FacebookLoginButton/index.js
- src/components/FirebaseGoogleLoginButton/index.js
- src/components/LoginGuest/index.js
- src/components/OrderList/index.js
- src/components/UpsellingPage/index.js
- src/index.js
Story: https://app.asana.com/0/1164464536714178/1207925083140181/f
> refactor: Add LoginGuest component and improvements

- src/components/AddressForm/index.js
- src/components/BusinessAndProductList/index.js
- src/components/BusinessReviews/index.js
- src/components/GpsButton/index.js
- The getNearestBusiness function in the AddressForm component has been updated to include a callback parameter. This allows for additional functionality to be executed after the nearest business is retrieved.
handleFavoriteBusiness method added to BusinessAndProductList component
- A new method, handleFavoriteBusiness, has been added to the BusinessAndProductList component. This method is responsible for adding or removing a business from the user's favorites list.
showEmptyComments prop added to BusinessReviews component
- The BusinessReviews component now accepts a new prop, showEmptyComments. When set to true, the component will display reviews with empty comments.
useEffect added to GpsButton component
- The GpsButton component now includes a useEffect hook that triggers the …
> refactor: Update getNearestBusiness function to include a callback parameter

- src/components/OrderListGroups/index.js
Story: https://app.asana.com/0/1164464536714178/1208458115011347/f
> Refactor order list groups component to improve code readability and maintainability

- src/components/UpsellingPage/index.js
Story: https://app.asana.com/0/1164464536714178/1208468965897326/f
> feat: add prop useSuggestiveUpselling

- src/components/BusinessReviews/index.js
- src/components/PaymentOptions/index.js
Story: https://app.asana.com/0/1164464536714178/1208468965897293/f
> Refactor payment options filter to include new stripe link

- src/components/PaymentOptionStripeLink/index.js
- src/index.js
Story: https://app.asana.com/0/1164464536714178/1208570774311634/f
> Add PaymentOptionStripeLink component

- src/components/Checkout/index.js
Story: https://app.asana.com/0/0/1208612983397325/f
> Refactor Checkout component to handle order redirection in customer mode

- src/components/PaymentOptionStripeLink/index.js
Story: https://app.asana.com/0/1164464536714178/1208602367363143/f
> Refactor PaymentOptionStripeLink component to handle error messages in setStripeLinkState

- src/components/OrderListGroups/index.js
Story: https://app.asana.com/0/1164464536714178/1208649897842249/f
> Refactor OrderListGroups component to improve code readability and maintainability

- src/components/UpsellingPage/index.js
Story: https://app.asana.com/0/1164464536714178/1208640832020884/f
> Refactor UpsellingPage component to handle suggestive upselling loading state

- src/contexts/LanguageContext/index.js
Story: https://app.asana.com/0/1164464536714178/1208725088686788/f
> Add useEffect to load default language based on project subdomain

- src/components/ProductForm/index.js
- src/contexts/WebsocketContext/index.js
Story: https://app.asana.com/0/1164464536714178/1208708493017751/f
> Fix optional chaining in ProductForm and improve error handling in WebsocketContext

- src/components/GpsButton/index.js
Story: https://app.asana.com/0/1164464536714178/1208821733814724/f
> Enhance error handling in GpsButton component to include error status

- src/components/AddressForm/index.js
- src/components/BusinessAndProductList/index.js
- src/components/Checkout/index.js
Story: https://app.asana.com/0/1164464536714178/1208821958285464/f
> Add order type handling and improve slug comparison logic

- src/components/BusinessAndProductList/index.js
Story: https://app.asana.com/0/1164464536714178/1209024639161642/f
> Refactor product mapping in BusinessAndProductList to include category slug

- src/components/Checkout/index.js
- src/components/MultiCheckout/index.js
Story: https://app.asana.com/0/1164464536714178/1209070383530960/f
> Refactor OrderListGroups component to conditionally leave order socket rooms

- src/components/PaymentOptions/index.js
- src/contexts/UtilsContext/index.js
Story: https://app.asana.com/0/1164464536714178/1209107907780188/f
> feat: enhance GiftCard payment methods with async token handling and cancellation support

- src/components/PaymentOptions/index.js
- src/contexts/UtilsContext/index.js
Story: https://app.asana.com/0/1164464536714178/1209107907780188/f
> feat: implement async fetching of gift card payment methods with cancellation support

- src/components/ProductOptionSuboption/index.js
Story: https://app.asana.com/0/1164464536714178/1209259258289778
> feat: Enhance pizza option suboption selection logic with advanced half-option handling

- src/components/Cart/index.js
- src/components/MultiCheckout/index.js
- src/contexts/OrderContext/index.js
- Update Cart component to support optional callback after cart modification
- Optimize MultiCheckout cart loading and dependency management
- Refine OrderContext cart state update logic
> fix: Improve cart update and multi-cart handling

- src/components/PaymentOptionStripeLink/index.js
Story: https://app.asana.com/0/1164464536714178/1209215390478092
> feat: Enhance Stripe Link payment with additional context and custom provider support

- src/components/MultiCartsPaymethodsAndWallets/index.js
- Implement deleteIndividualWallet method to remove wallets from specific carts
- Add useEffect hook to handle wallet deletion for individual carts
- Integrate OrderContext to update cart state after wallet removal
> feat: Add wallet deletion functionality for individual carts

- src/components/OrderList/index.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1209638275881419?focus=true
> feat: Implement handleRemoveCart method to clear products from cart

- src/components/BusinessList/index.js
Story: https://app.asana.com/1/306583973076188/project/1200333079319160/task/1210129150136425?focus=true
> feat: Update pagination parameters in BusinessList component and modify propsToFetch array

- src/components/PaymentOptions/index.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1210263381590462?focus=true
> fix: Update payment method selection logic to include fallback for paymethod selection

- src/components/AddressForm/index.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1210284222555005?focus=true
> fix: Update propsToFetch in AddressForm to include 'description'

- src/components/GoogleMaps/index.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1210416158984700?focus=true
> feat: Add initialBusinessesToCenter prop to GoogleMaps for controlled centering

- src/components/OrderDetails/index.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1210487073040074?focus=true
> fix: Refactor order status handling to support FormData and improve error logging in OrderDetails component

- src/components/PageBanner/index.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1210582357293727?focus=true
> feat: Add isProjectChange prop and update useEffect to handle project changes in PageBanner component

- src/components/Checkout/index.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1210686665968367?focus=true
> feat: Update defaultProps in Checkout component to include 'description' in propsToFetch

- src/contexts/OrderContext/index.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1210815039073653?focus=true
> fix: Add 'X-App-X' header to OrderProvider for enhanced socket communication

- src/components/Checkout/index.js
Story: https://app.asana.com/1/306583973076188/task/1210813006648947?focus=true
> fix: Add default delivery option selection logic in Checkout component

- src/components/BusinessAndProductList/index.js
- src/components/ProductForm/index.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1210815508646877?focus=true
> fix: Sort extras, options, and suboptions by rank in BusinessAndProductList and ProductForm components

- src/components/LoginForm/index.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1210801178150200?focus=true
> fix: Add custom headers to login request for enhanced authentication

- src/components/ProductForm/index.js
Story: https://app.asana.com/1/306583973076188/task/1210931617315900
> fix: Update ProductForm logic to prevent multiple coupons when not allowed

- native/src/contexts/OrderingContext/index.js
- src/contexts/OrderingContext/index.js
- src/contexts/UtilsContext/index.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1209439851714073?focus=true
> fix: Update UtilsProviders to handle currency changes and improve price parsing logic

- src/components/GoogleMaps/index.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1211173566709341?focus=true
> fix: Implement active InfoWindow management in Google Maps component to ensure only one InfoWindow is open at a time
